// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-nHyYibnqyQTHbywXDoxnCasBzf13mqo',
    appId: '1:789191484521:web:6d448880e647fac2c86ef8',
    messagingSenderId: '789191484521',
    projectId: 'to-do-list-bb383',
    authDomain: 'to-do-list-bb383.firebaseapp.com',
    storageBucket: 'to-do-list-bb383.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9QIoe7eT3ShmcWw0E2gSAG6t3kPB7g0A',
    appId: '1:789191484521:android:ce17fa1c994c0d46c86ef8',
    messagingSenderId: '789191484521',
    projectId: 'to-do-list-bb383',
    storageBucket: 'to-do-list-bb383.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI8FSlTgiOfW6p5_eN4GHTQ8pxIwgf4v0',
    appId: '1:789191484521:ios:4da01d75e64ddd7ac86ef8',
    messagingSenderId: '789191484521',
    projectId: 'to-do-list-bb383',
    storageBucket: 'to-do-list-bb383.appspot.com',
    iosClientId: '789191484521-702ij8eq638ij1hk3vmcpe2kpu59u0f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI8FSlTgiOfW6p5_eN4GHTQ8pxIwgf4v0',
    appId: '1:789191484521:ios:4da01d75e64ddd7ac86ef8',
    messagingSenderId: '789191484521',
    projectId: 'to-do-list-bb383',
    storageBucket: 'to-do-list-bb383.appspot.com',
    iosClientId: '789191484521-702ij8eq638ij1hk3vmcpe2kpu59u0f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoList',
  );
}
